services:
  gateway:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: postit-gateway-dev
    ports:
      - "8901:80"
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    container_name: postit-client-dev
    environment:
      - PORT=4800
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: postit-server-dev
    environment:
      - SERVER_PORT=8501
      - JWT_SECRET=75867AA2039B13075BB92152F457AC6BBA6E7D3459AA04DA8F1EE1A921CC2170
      - JWT_ISSUER=postit.com
      - SPRING_R2DBC_URL=r2dbc:mysql://postit-db:3306/dockerdb
      - SPRING_R2DBC_USERNAME=postit
      - SPRING_R2DBC_PASSWORD=complexpassword
  db:
    image: mysql:8.0-bookworm
    container_name: postit-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=postit
      - MYSQL_PASSWORD=complexpassword
      - MYSQL_DATABASE=dockerdb

networks:
  post-it-network:
    driver: bridge
